'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ASfollowService
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ASfollowService.ASfollowServiceSoap")>  _
    Public Interface ASfollowServiceSoap
        
        'CODEGEN: Generating message contract since element name pingResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function ping(ByVal request As ASfollowService.pingRequest) As ASfollowService.pingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function pingAsync(ByVal request As ASfollowService.pingRequest) As System.Threading.Tasks.Task(Of ASfollowService.pingResponse)
        
        'CODEGEN: Generating message contract since element name aboutResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/about", ReplyAction:="*")>  _
        Function about(ByVal request As ASfollowService.aboutRequest) As ASfollowService.aboutResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/about", ReplyAction:="*")>  _
        Function aboutAsync(ByVal request As ASfollowService.aboutRequest) As System.Threading.Tasks.Task(Of ASfollowService.aboutResponse)
        
        'CODEGEN: Generating message contract since element name shareInfoResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/shareInfo", ReplyAction:="*")>  _
        Function shareInfo(ByVal request As ASfollowService.shareInfoRequest) As ASfollowService.shareInfoResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/shareInfo", ReplyAction:="*")>  _
        Function shareInfoAsync(ByVal request As ASfollowService.shareInfoRequest) As System.Threading.Tasks.Task(Of ASfollowService.shareInfoResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class pingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ping", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ASfollowService.pingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ASfollowService.pingRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class pingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class pingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="pingResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ASfollowService.pingResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ASfollowService.pingResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class pingResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pingResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pingResult As String)
            MyBase.New
            Me.pingResult = pingResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aboutRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="about", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ASfollowService.aboutRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ASfollowService.aboutRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class aboutRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aboutResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="aboutResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ASfollowService.aboutResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ASfollowService.aboutResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class aboutResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public aboutResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal aboutResult As String)
            MyBase.New
            Me.aboutResult = aboutResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class shareInfoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="shareInfo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ASfollowService.shareInfoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ASfollowService.shareInfoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class shareInfoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class shareInfoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="shareInfoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ASfollowService.shareInfoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ASfollowService.shareInfoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class shareInfoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public shareInfoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal shareInfoResult As String)
            MyBase.New
            Me.shareInfoResult = shareInfoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ASfollowServiceSoapChannel
        Inherits ASfollowService.ASfollowServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ASfollowServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ASfollowService.ASfollowServiceSoap)
        Implements ASfollowService.ASfollowServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ASfollowService_ASfollowServiceSoap_ping(ByVal request As ASfollowService.pingRequest) As ASfollowService.pingResponse Implements ASfollowService.ASfollowServiceSoap.ping
            Return MyBase.Channel.ping(request)
        End Function
        
        Public Function ping() As String
            Dim inValue As ASfollowService.pingRequest = New ASfollowService.pingRequest()
            inValue.Body = New ASfollowService.pingRequestBody()
            Dim retVal As ASfollowService.pingResponse = CType(Me,ASfollowService.ASfollowServiceSoap).ping(inValue)
            Return retVal.Body.pingResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ASfollowService_ASfollowServiceSoap_pingAsync(ByVal request As ASfollowService.pingRequest) As System.Threading.Tasks.Task(Of ASfollowService.pingResponse) Implements ASfollowService.ASfollowServiceSoap.pingAsync
            Return MyBase.Channel.pingAsync(request)
        End Function
        
        Public Function pingAsync() As System.Threading.Tasks.Task(Of ASfollowService.pingResponse)
            Dim inValue As ASfollowService.pingRequest = New ASfollowService.pingRequest()
            inValue.Body = New ASfollowService.pingRequestBody()
            Return CType(Me,ASfollowService.ASfollowServiceSoap).pingAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ASfollowService_ASfollowServiceSoap_about(ByVal request As ASfollowService.aboutRequest) As ASfollowService.aboutResponse Implements ASfollowService.ASfollowServiceSoap.about
            Return MyBase.Channel.about(request)
        End Function
        
        Public Function about() As String
            Dim inValue As ASfollowService.aboutRequest = New ASfollowService.aboutRequest()
            inValue.Body = New ASfollowService.aboutRequestBody()
            Dim retVal As ASfollowService.aboutResponse = CType(Me,ASfollowService.ASfollowServiceSoap).about(inValue)
            Return retVal.Body.aboutResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ASfollowService_ASfollowServiceSoap_aboutAsync(ByVal request As ASfollowService.aboutRequest) As System.Threading.Tasks.Task(Of ASfollowService.aboutResponse) Implements ASfollowService.ASfollowServiceSoap.aboutAsync
            Return MyBase.Channel.aboutAsync(request)
        End Function
        
        Public Function aboutAsync() As System.Threading.Tasks.Task(Of ASfollowService.aboutResponse)
            Dim inValue As ASfollowService.aboutRequest = New ASfollowService.aboutRequest()
            inValue.Body = New ASfollowService.aboutRequestBody()
            Return CType(Me,ASfollowService.ASfollowServiceSoap).aboutAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ASfollowService_ASfollowServiceSoap_shareInfo(ByVal request As ASfollowService.shareInfoRequest) As ASfollowService.shareInfoResponse Implements ASfollowService.ASfollowServiceSoap.shareInfo
            Return MyBase.Channel.shareInfo(request)
        End Function
        
        Public Function shareInfo() As String
            Dim inValue As ASfollowService.shareInfoRequest = New ASfollowService.shareInfoRequest()
            inValue.Body = New ASfollowService.shareInfoRequestBody()
            Dim retVal As ASfollowService.shareInfoResponse = CType(Me,ASfollowService.ASfollowServiceSoap).shareInfo(inValue)
            Return retVal.Body.shareInfoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ASfollowService_ASfollowServiceSoap_shareInfoAsync(ByVal request As ASfollowService.shareInfoRequest) As System.Threading.Tasks.Task(Of ASfollowService.shareInfoResponse) Implements ASfollowService.ASfollowServiceSoap.shareInfoAsync
            Return MyBase.Channel.shareInfoAsync(request)
        End Function
        
        Public Function shareInfoAsync() As System.Threading.Tasks.Task(Of ASfollowService.shareInfoResponse)
            Dim inValue As ASfollowService.shareInfoRequest = New ASfollowService.shareInfoRequest()
            inValue.Body = New ASfollowService.shareInfoRequestBody()
            Return CType(Me,ASfollowService.ASfollowServiceSoap).shareInfoAsync(inValue)
        End Function
    End Class
End Namespace
