'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace StepService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="step", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class [step]
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private step_idField As Long
        
        Private action_idField As Long
        
        Private tag_idField As System.Nullable(Of Long)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private textField As String
        
        Private priorityField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private cronField As String
        
        Private amountField As System.Nullable(Of Integer)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private checkedField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private descriptionField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property step_id() As Long
            Get
                Return Me.step_idField
            End Get
            Set
                If (Me.step_idField.Equals(value) <> true) Then
                    Me.step_idField = value
                    Me.RaisePropertyChanged("step_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property action_id() As Long
            Get
                Return Me.action_idField
            End Get
            Set
                If (Me.action_idField.Equals(value) <> true) Then
                    Me.action_idField = value
                    Me.RaisePropertyChanged("action_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=2)>  _
        Public Property tag_id() As System.Nullable(Of Long)
            Get
                Return Me.tag_idField
            End Get
            Set
                If (Me.tag_idField.Equals(value) <> true) Then
                    Me.tag_idField = value
                    Me.RaisePropertyChanged("tag_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Property text() As String
            Get
                Return Me.textField
            End Get
            Set
                If (Object.ReferenceEquals(Me.textField, value) <> true) Then
                    Me.textField = value
                    Me.RaisePropertyChanged("text")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property priority() As System.Nullable(Of Integer)
            Get
                Return Me.priorityField
            End Get
            Set
                If (Me.priorityField.Equals(value) <> true) Then
                    Me.priorityField = value
                    Me.RaisePropertyChanged("priority")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Property cron() As String
            Get
                Return Me.cronField
            End Get
            Set
                If (Object.ReferenceEquals(Me.cronField, value) <> true) Then
                    Me.cronField = value
                    Me.RaisePropertyChanged("cron")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=6)>  _
        Public Property amount() As System.Nullable(Of Integer)
            Get
                Return Me.amountField
            End Get
            Set
                If (Me.amountField.Equals(value) <> true) Then
                    Me.amountField = value
                    Me.RaisePropertyChanged("amount")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Property checked() As String
            Get
                Return Me.checkedField
            End Get
            Set
                If (Object.ReferenceEquals(Me.checkedField, value) <> true) Then
                    Me.checkedField = value
                    Me.RaisePropertyChanged("checked")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Property description() As String
            Get
                Return Me.descriptionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.descriptionField, value) <> true) Then
                    Me.descriptionField = value
                    Me.RaisePropertyChanged("description")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfStep", [Namespace]:="http://tempuri.org/", ItemName:="step"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfStep
        Inherits System.Collections.Generic.List(Of StepService.[step])
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="StepService.StepServiceSoap")>  _
    Public Interface StepServiceSoap
        
        'CODEGEN: Generating message contract since element name pingResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function ping(ByVal request As StepService.pingRequest) As StepService.pingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function pingAsync(ByVal request As StepService.pingRequest) As System.Threading.Tasks.Task(Of StepService.pingResponse)
        
        'CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addStep", ReplyAction:="*")>  _
        Function addStep(ByVal request As StepService.addStepRequest) As StepService.addStepResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addStep", ReplyAction:="*")>  _
        Function addStepAsync(ByVal request As StepService.addStepRequest) As System.Threading.Tasks.Task(Of StepService.addStepResponse)
        
        'CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addStepByActionIdAndText", ReplyAction:="*")>  _
        Function addStepByActionIdAndText(ByVal request As StepService.addStepByActionIdAndTextRequest) As StepService.addStepByActionIdAndTextResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addStepByActionIdAndText", ReplyAction:="*")>  _
        Function addStepByActionIdAndTextAsync(ByVal request As StepService.addStepByActionIdAndTextRequest) As System.Threading.Tasks.Task(Of StepService.addStepByActionIdAndTextResponse)
        
        'CODEGEN: Generating message contract since element name text from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateStep", ReplyAction:="*")>  _
        Function updateStep(ByVal request As StepService.updateStepRequest) As StepService.updateStepResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateStep", ReplyAction:="*")>  _
        Function updateStepAsync(ByVal request As StepService.updateStepRequest) As System.Threading.Tasks.Task(Of StepService.updateStepResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/setStepChecked", ReplyAction:="*")>  _
        Function setStepChecked(ByVal stepId As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/setStepChecked", ReplyAction:="*")>  _
        Function setStepCheckedAsync(ByVal stepId As Long) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deleteStep", ReplyAction:="*")>  _
        Function deleteStep(ByVal stepId As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deleteStep", ReplyAction:="*")>  _
        Function deleteStepAsync(ByVal stepId As Long) As System.Threading.Tasks.Task(Of Boolean)
        
        'CODEGEN: Generating message contract since element name getStepByStepIdResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getStepByStepId", ReplyAction:="*")>  _
        Function getStepByStepId(ByVal request As StepService.getStepByStepIdRequest) As StepService.getStepByStepIdResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getStepByStepId", ReplyAction:="*")>  _
        Function getStepByStepIdAsync(ByVal request As StepService.getStepByStepIdRequest) As System.Threading.Tasks.Task(Of StepService.getStepByStepIdResponse)
        
        'CODEGEN: Generating message contract since element name getStepsByActionIdResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getStepsByActionId", ReplyAction:="*")>  _
        Function getStepsByActionId(ByVal request As StepService.getStepsByActionIdRequest) As StepService.getStepsByActionIdResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getStepsByActionId", ReplyAction:="*")>  _
        Function getStepsByActionIdAsync(ByVal request As StepService.getStepsByActionIdRequest) As System.Threading.Tasks.Task(Of StepService.getStepsByActionIdResponse)
        
        'CODEGEN: Generating message contract since element name getStepsByTagIdResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getStepsByTagId", ReplyAction:="*")>  _
        Function getStepsByTagId(ByVal request As StepService.getStepsByTagIdRequest) As StepService.getStepsByTagIdResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getStepsByTagId", ReplyAction:="*")>  _
        Function getStepsByTagIdAsync(ByVal request As StepService.getStepsByTagIdRequest) As System.Threading.Tasks.Task(Of StepService.getStepsByTagIdResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/refreshSteps", ReplyAction:="*")>  _
        Function refreshSteps() As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/refreshSteps", ReplyAction:="*")>  _
        Function refreshStepsAsync() As System.Threading.Tasks.Task(Of Boolean)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class pingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ping", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.pingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.pingRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class pingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class pingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="pingResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.pingResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.pingResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class pingResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pingResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pingResult As String)
            MyBase.New
            Me.pingResult = pingResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addStepRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addStep", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.addStepRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.addStepRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addStepRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public actionId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public text As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public tagId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public priority As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public cron As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=5)>  _
        Public amount As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public checked As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public description As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal actionId As Integer, ByVal text As String, ByVal tagId As Integer, ByVal priority As Integer, ByVal cron As String, ByVal amount As Integer, ByVal checked As String, ByVal description As String)
            MyBase.New
            Me.actionId = actionId
            Me.text = text
            Me.tagId = tagId
            Me.priority = priority
            Me.cron = cron
            Me.amount = amount
            Me.checked = checked
            Me.description = description
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addStepResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addStepResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.addStepResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.addStepResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addStepResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public addStepResult As StepService.[step]
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal addStepResult As StepService.[step])
            MyBase.New
            Me.addStepResult = addStepResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addStepByActionIdAndTextRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addStepByActionIdAndText", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.addStepByActionIdAndTextRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.addStepByActionIdAndTextRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addStepByActionIdAndTextRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public actionId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public text As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal actionId As Integer, ByVal text As String)
            MyBase.New
            Me.actionId = actionId
            Me.text = text
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addStepByActionIdAndTextResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addStepByActionIdAndTextResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.addStepByActionIdAndTextResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.addStepByActionIdAndTextResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addStepByActionIdAndTextResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public addStepByActionIdAndTextResult As StepService.[step]
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal addStepByActionIdAndTextResult As StepService.[step])
            MyBase.New
            Me.addStepByActionIdAndTextResult = addStepByActionIdAndTextResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateStepRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateStep", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.updateStepRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.updateStepRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateStepRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public stepId As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public actionId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public text As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=3)>  _
        Public tagId As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=4)>  _
        Public priority As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public cron As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=6)>  _
        Public amount As Integer
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public checked As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public description As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal stepId As Long, ByVal actionId As Integer, ByVal text As String, ByVal tagId As Integer, ByVal priority As Integer, ByVal cron As String, ByVal amount As Integer, ByVal checked As String, ByVal description As String)
            MyBase.New
            Me.stepId = stepId
            Me.actionId = actionId
            Me.text = text
            Me.tagId = tagId
            Me.priority = priority
            Me.cron = cron
            Me.amount = amount
            Me.checked = checked
            Me.description = description
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateStepResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateStepResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.updateStepResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.updateStepResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateStepResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public updateStepResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updateStepResult As Boolean)
            MyBase.New
            Me.updateStepResult = updateStepResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getStepByStepIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getStepByStepId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.getStepByStepIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.getStepByStepIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getStepByStepIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public stepId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal stepId As Integer)
            MyBase.New
            Me.stepId = stepId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getStepByStepIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getStepByStepIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.getStepByStepIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.getStepByStepIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getStepByStepIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getStepByStepIdResult As StepService.[step]
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getStepByStepIdResult As StepService.[step])
            MyBase.New
            Me.getStepByStepIdResult = getStepByStepIdResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getStepsByActionIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getStepsByActionId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.getStepsByActionIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.getStepsByActionIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getStepsByActionIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public actionId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal actionId As Integer)
            MyBase.New
            Me.actionId = actionId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getStepsByActionIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getStepsByActionIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.getStepsByActionIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.getStepsByActionIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getStepsByActionIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getStepsByActionIdResult As StepService.ArrayOfStep
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getStepsByActionIdResult As StepService.ArrayOfStep)
            MyBase.New
            Me.getStepsByActionIdResult = getStepsByActionIdResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getStepsByTagIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getStepsByTagId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.getStepsByTagIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.getStepsByTagIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getStepsByTagIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public tagId As Integer
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal tagId As Integer)
            MyBase.New
            Me.tagId = tagId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getStepsByTagIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getStepsByTagIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As StepService.getStepsByTagIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As StepService.getStepsByTagIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getStepsByTagIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getStepsByTagIdResult As StepService.ArrayOfStep
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getStepsByTagIdResult As StepService.ArrayOfStep)
            MyBase.New
            Me.getStepsByTagIdResult = getStepsByTagIdResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface StepServiceSoapChannel
        Inherits StepService.StepServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class StepServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of StepService.StepServiceSoap)
        Implements StepService.StepServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_ping(ByVal request As StepService.pingRequest) As StepService.pingResponse Implements StepService.StepServiceSoap.ping
            Return MyBase.Channel.ping(request)
        End Function
        
        Public Function ping() As String
            Dim inValue As StepService.pingRequest = New StepService.pingRequest()
            inValue.Body = New StepService.pingRequestBody()
            Dim retVal As StepService.pingResponse = CType(Me,StepService.StepServiceSoap).ping(inValue)
            Return retVal.Body.pingResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_pingAsync(ByVal request As StepService.pingRequest) As System.Threading.Tasks.Task(Of StepService.pingResponse) Implements StepService.StepServiceSoap.pingAsync
            Return MyBase.Channel.pingAsync(request)
        End Function
        
        Public Function pingAsync() As System.Threading.Tasks.Task(Of StepService.pingResponse)
            Dim inValue As StepService.pingRequest = New StepService.pingRequest()
            inValue.Body = New StepService.pingRequestBody()
            Return CType(Me,StepService.StepServiceSoap).pingAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_addStep(ByVal request As StepService.addStepRequest) As StepService.addStepResponse Implements StepService.StepServiceSoap.addStep
            Return MyBase.Channel.addStep(request)
        End Function
        
        Public Function addStep(ByVal actionId As Integer, ByVal text As String, ByVal tagId As Integer, ByVal priority As Integer, ByVal cron As String, ByVal amount As Integer, ByVal checked As String, ByVal description As String) As StepService.[step]
            Dim inValue As StepService.addStepRequest = New StepService.addStepRequest()
            inValue.Body = New StepService.addStepRequestBody()
            inValue.Body.actionId = actionId
            inValue.Body.text = text
            inValue.Body.tagId = tagId
            inValue.Body.priority = priority
            inValue.Body.cron = cron
            inValue.Body.amount = amount
            inValue.Body.checked = checked
            inValue.Body.description = description
            Dim retVal As StepService.addStepResponse = CType(Me,StepService.StepServiceSoap).addStep(inValue)
            Return retVal.Body.addStepResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_addStepAsync(ByVal request As StepService.addStepRequest) As System.Threading.Tasks.Task(Of StepService.addStepResponse) Implements StepService.StepServiceSoap.addStepAsync
            Return MyBase.Channel.addStepAsync(request)
        End Function
        
        Public Function addStepAsync(ByVal actionId As Integer, ByVal text As String, ByVal tagId As Integer, ByVal priority As Integer, ByVal cron As String, ByVal amount As Integer, ByVal checked As String, ByVal description As String) As System.Threading.Tasks.Task(Of StepService.addStepResponse)
            Dim inValue As StepService.addStepRequest = New StepService.addStepRequest()
            inValue.Body = New StepService.addStepRequestBody()
            inValue.Body.actionId = actionId
            inValue.Body.text = text
            inValue.Body.tagId = tagId
            inValue.Body.priority = priority
            inValue.Body.cron = cron
            inValue.Body.amount = amount
            inValue.Body.checked = checked
            inValue.Body.description = description
            Return CType(Me,StepService.StepServiceSoap).addStepAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_addStepByActionIdAndText(ByVal request As StepService.addStepByActionIdAndTextRequest) As StepService.addStepByActionIdAndTextResponse Implements StepService.StepServiceSoap.addStepByActionIdAndText
            Return MyBase.Channel.addStepByActionIdAndText(request)
        End Function
        
        Public Function addStepByActionIdAndText(ByVal actionId As Integer, ByVal text As String) As StepService.[step]
            Dim inValue As StepService.addStepByActionIdAndTextRequest = New StepService.addStepByActionIdAndTextRequest()
            inValue.Body = New StepService.addStepByActionIdAndTextRequestBody()
            inValue.Body.actionId = actionId
            inValue.Body.text = text
            Dim retVal As StepService.addStepByActionIdAndTextResponse = CType(Me,StepService.StepServiceSoap).addStepByActionIdAndText(inValue)
            Return retVal.Body.addStepByActionIdAndTextResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_addStepByActionIdAndTextAsync(ByVal request As StepService.addStepByActionIdAndTextRequest) As System.Threading.Tasks.Task(Of StepService.addStepByActionIdAndTextResponse) Implements StepService.StepServiceSoap.addStepByActionIdAndTextAsync
            Return MyBase.Channel.addStepByActionIdAndTextAsync(request)
        End Function
        
        Public Function addStepByActionIdAndTextAsync(ByVal actionId As Integer, ByVal text As String) As System.Threading.Tasks.Task(Of StepService.addStepByActionIdAndTextResponse)
            Dim inValue As StepService.addStepByActionIdAndTextRequest = New StepService.addStepByActionIdAndTextRequest()
            inValue.Body = New StepService.addStepByActionIdAndTextRequestBody()
            inValue.Body.actionId = actionId
            inValue.Body.text = text
            Return CType(Me,StepService.StepServiceSoap).addStepByActionIdAndTextAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_updateStep(ByVal request As StepService.updateStepRequest) As StepService.updateStepResponse Implements StepService.StepServiceSoap.updateStep
            Return MyBase.Channel.updateStep(request)
        End Function
        
        Public Function updateStep(ByVal stepId As Long, ByVal actionId As Integer, ByVal text As String, ByVal tagId As Integer, ByVal priority As Integer, ByVal cron As String, ByVal amount As Integer, ByVal checked As String, ByVal description As String) As Boolean
            Dim inValue As StepService.updateStepRequest = New StepService.updateStepRequest()
            inValue.Body = New StepService.updateStepRequestBody()
            inValue.Body.stepId = stepId
            inValue.Body.actionId = actionId
            inValue.Body.text = text
            inValue.Body.tagId = tagId
            inValue.Body.priority = priority
            inValue.Body.cron = cron
            inValue.Body.amount = amount
            inValue.Body.checked = checked
            inValue.Body.description = description
            Dim retVal As StepService.updateStepResponse = CType(Me,StepService.StepServiceSoap).updateStep(inValue)
            Return retVal.Body.updateStepResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_updateStepAsync(ByVal request As StepService.updateStepRequest) As System.Threading.Tasks.Task(Of StepService.updateStepResponse) Implements StepService.StepServiceSoap.updateStepAsync
            Return MyBase.Channel.updateStepAsync(request)
        End Function
        
        Public Function updateStepAsync(ByVal stepId As Long, ByVal actionId As Integer, ByVal text As String, ByVal tagId As Integer, ByVal priority As Integer, ByVal cron As String, ByVal amount As Integer, ByVal checked As String, ByVal description As String) As System.Threading.Tasks.Task(Of StepService.updateStepResponse)
            Dim inValue As StepService.updateStepRequest = New StepService.updateStepRequest()
            inValue.Body = New StepService.updateStepRequestBody()
            inValue.Body.stepId = stepId
            inValue.Body.actionId = actionId
            inValue.Body.text = text
            inValue.Body.tagId = tagId
            inValue.Body.priority = priority
            inValue.Body.cron = cron
            inValue.Body.amount = amount
            inValue.Body.checked = checked
            inValue.Body.description = description
            Return CType(Me,StepService.StepServiceSoap).updateStepAsync(inValue)
        End Function
        
        Public Function setStepChecked(ByVal stepId As Long) As Boolean Implements StepService.StepServiceSoap.setStepChecked
            Return MyBase.Channel.setStepChecked(stepId)
        End Function
        
        Public Function setStepCheckedAsync(ByVal stepId As Long) As System.Threading.Tasks.Task(Of Boolean) Implements StepService.StepServiceSoap.setStepCheckedAsync
            Return MyBase.Channel.setStepCheckedAsync(stepId)
        End Function
        
        Public Function deleteStep(ByVal stepId As Long) As Boolean Implements StepService.StepServiceSoap.deleteStep
            Return MyBase.Channel.deleteStep(stepId)
        End Function
        
        Public Function deleteStepAsync(ByVal stepId As Long) As System.Threading.Tasks.Task(Of Boolean) Implements StepService.StepServiceSoap.deleteStepAsync
            Return MyBase.Channel.deleteStepAsync(stepId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_getStepByStepId(ByVal request As StepService.getStepByStepIdRequest) As StepService.getStepByStepIdResponse Implements StepService.StepServiceSoap.getStepByStepId
            Return MyBase.Channel.getStepByStepId(request)
        End Function
        
        Public Function getStepByStepId(ByVal stepId As Integer) As StepService.[step]
            Dim inValue As StepService.getStepByStepIdRequest = New StepService.getStepByStepIdRequest()
            inValue.Body = New StepService.getStepByStepIdRequestBody()
            inValue.Body.stepId = stepId
            Dim retVal As StepService.getStepByStepIdResponse = CType(Me,StepService.StepServiceSoap).getStepByStepId(inValue)
            Return retVal.Body.getStepByStepIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_getStepByStepIdAsync(ByVal request As StepService.getStepByStepIdRequest) As System.Threading.Tasks.Task(Of StepService.getStepByStepIdResponse) Implements StepService.StepServiceSoap.getStepByStepIdAsync
            Return MyBase.Channel.getStepByStepIdAsync(request)
        End Function
        
        Public Function getStepByStepIdAsync(ByVal stepId As Integer) As System.Threading.Tasks.Task(Of StepService.getStepByStepIdResponse)
            Dim inValue As StepService.getStepByStepIdRequest = New StepService.getStepByStepIdRequest()
            inValue.Body = New StepService.getStepByStepIdRequestBody()
            inValue.Body.stepId = stepId
            Return CType(Me,StepService.StepServiceSoap).getStepByStepIdAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_getStepsByActionId(ByVal request As StepService.getStepsByActionIdRequest) As StepService.getStepsByActionIdResponse Implements StepService.StepServiceSoap.getStepsByActionId
            Return MyBase.Channel.getStepsByActionId(request)
        End Function
        
        Public Function getStepsByActionId(ByVal actionId As Integer) As StepService.ArrayOfStep
            Dim inValue As StepService.getStepsByActionIdRequest = New StepService.getStepsByActionIdRequest()
            inValue.Body = New StepService.getStepsByActionIdRequestBody()
            inValue.Body.actionId = actionId
            Dim retVal As StepService.getStepsByActionIdResponse = CType(Me,StepService.StepServiceSoap).getStepsByActionId(inValue)
            Return retVal.Body.getStepsByActionIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_getStepsByActionIdAsync(ByVal request As StepService.getStepsByActionIdRequest) As System.Threading.Tasks.Task(Of StepService.getStepsByActionIdResponse) Implements StepService.StepServiceSoap.getStepsByActionIdAsync
            Return MyBase.Channel.getStepsByActionIdAsync(request)
        End Function
        
        Public Function getStepsByActionIdAsync(ByVal actionId As Integer) As System.Threading.Tasks.Task(Of StepService.getStepsByActionIdResponse)
            Dim inValue As StepService.getStepsByActionIdRequest = New StepService.getStepsByActionIdRequest()
            inValue.Body = New StepService.getStepsByActionIdRequestBody()
            inValue.Body.actionId = actionId
            Return CType(Me,StepService.StepServiceSoap).getStepsByActionIdAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_getStepsByTagId(ByVal request As StepService.getStepsByTagIdRequest) As StepService.getStepsByTagIdResponse Implements StepService.StepServiceSoap.getStepsByTagId
            Return MyBase.Channel.getStepsByTagId(request)
        End Function
        
        Public Function getStepsByTagId(ByVal tagId As Integer) As StepService.ArrayOfStep
            Dim inValue As StepService.getStepsByTagIdRequest = New StepService.getStepsByTagIdRequest()
            inValue.Body = New StepService.getStepsByTagIdRequestBody()
            inValue.Body.tagId = tagId
            Dim retVal As StepService.getStepsByTagIdResponse = CType(Me,StepService.StepServiceSoap).getStepsByTagId(inValue)
            Return retVal.Body.getStepsByTagIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function StepService_StepServiceSoap_getStepsByTagIdAsync(ByVal request As StepService.getStepsByTagIdRequest) As System.Threading.Tasks.Task(Of StepService.getStepsByTagIdResponse) Implements StepService.StepServiceSoap.getStepsByTagIdAsync
            Return MyBase.Channel.getStepsByTagIdAsync(request)
        End Function
        
        Public Function getStepsByTagIdAsync(ByVal tagId As Integer) As System.Threading.Tasks.Task(Of StepService.getStepsByTagIdResponse)
            Dim inValue As StepService.getStepsByTagIdRequest = New StepService.getStepsByTagIdRequest()
            inValue.Body = New StepService.getStepsByTagIdRequestBody()
            inValue.Body.tagId = tagId
            Return CType(Me,StepService.StepServiceSoap).getStepsByTagIdAsync(inValue)
        End Function
        
        Public Function refreshSteps() As Boolean Implements StepService.StepServiceSoap.refreshSteps
            Return MyBase.Channel.refreshSteps
        End Function
        
        Public Function refreshStepsAsync() As System.Threading.Tasks.Task(Of Boolean) Implements StepService.StepServiceSoap.refreshStepsAsync
            Return MyBase.Channel.refreshStepsAsync
        End Function
    End Class
End Namespace
