'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ActionService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="action", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class action
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private action_idField As Long
        
        Private unit_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property action_id() As Long
            Get
                Return Me.action_idField
            End Get
            Set
                If (Me.action_idField.Equals(value) <> true) Then
                    Me.action_idField = value
                    Me.RaisePropertyChanged("action_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property unit_id() As Long
            Get
                Return Me.unit_idField
            End Get
            Set
                If (Me.unit_idField.Equals(value) <> true) Then
                    Me.unit_idField = value
                    Me.RaisePropertyChanged("unit_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfAction", [Namespace]:="http://tempuri.org/", ItemName:="action"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfAction
        Inherits System.Collections.Generic.List(Of ActionService.action)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ActionService.ActionServiceSoap")>  _
    Public Interface ActionServiceSoap
        
        'CODEGEN: Generating message contract since element name pingResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function ping(ByVal request As ActionService.pingRequest) As ActionService.pingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function pingAsync(ByVal request As ActionService.pingRequest) As System.Threading.Tasks.Task(Of ActionService.pingResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addActionByNameAndUnitId", ReplyAction:="*")>  _
        Function addActionByNameAndUnitId(ByVal request As ActionService.addActionByNameAndUnitIdRequest) As ActionService.addActionByNameAndUnitIdResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addActionByNameAndUnitId", ReplyAction:="*")>  _
        Function addActionByNameAndUnitIdAsync(ByVal request As ActionService.addActionByNameAndUnitIdRequest) As System.Threading.Tasks.Task(Of ActionService.addActionByNameAndUnitIdResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateAction", ReplyAction:="*")>  _
        Function updateAction(ByVal request As ActionService.updateActionRequest) As ActionService.updateActionResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateAction", ReplyAction:="*")>  _
        Function updateActionAsync(ByVal request As ActionService.updateActionRequest) As System.Threading.Tasks.Task(Of ActionService.updateActionResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deleteAction", ReplyAction:="*")>  _
        Function deleteAction(ByVal actionId As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deleteAction", ReplyAction:="*")>  _
        Function deleteActionAsync(ByVal actionId As Long) As System.Threading.Tasks.Task(Of Boolean)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getActionByName", ReplyAction:="*")>  _
        Function getActionByName(ByVal request As ActionService.getActionByNameRequest) As ActionService.getActionByNameResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getActionByName", ReplyAction:="*")>  _
        Function getActionByNameAsync(ByVal request As ActionService.getActionByNameRequest) As System.Threading.Tasks.Task(Of ActionService.getActionByNameResponse)
        
        'CODEGEN: Generating message contract since element name getActionsByUnitIdResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getActionsByUnitId", ReplyAction:="*")>  _
        Function getActionsByUnitId(ByVal request As ActionService.getActionsByUnitIdRequest) As ActionService.getActionsByUnitIdResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getActionsByUnitId", ReplyAction:="*")>  _
        Function getActionsByUnitIdAsync(ByVal request As ActionService.getActionsByUnitIdRequest) As System.Threading.Tasks.Task(Of ActionService.getActionsByUnitIdResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class pingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ping", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.pingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.pingRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class pingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class pingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="pingResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.pingResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.pingResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class pingResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pingResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pingResult As String)
            MyBase.New
            Me.pingResult = pingResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addActionByNameAndUnitIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addActionByNameAndUnitId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.addActionByNameAndUnitIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.addActionByNameAndUnitIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addActionByNameAndUnitIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public unitId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String, ByVal unitId As Long)
            MyBase.New
            Me.name = name
            Me.unitId = unitId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addActionByNameAndUnitIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addActionByNameAndUnitIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.addActionByNameAndUnitIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.addActionByNameAndUnitIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addActionByNameAndUnitIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public addActionByNameAndUnitIdResult As ActionService.action
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal addActionByNameAndUnitIdResult As ActionService.action)
            MyBase.New
            Me.addActionByNameAndUnitIdResult = addActionByNameAndUnitIdResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateActionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateAction", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.updateActionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.updateActionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateActionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public unitId As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public actionId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String, ByVal unitId As Long, ByVal actionId As Long)
            MyBase.New
            Me.name = name
            Me.unitId = unitId
            Me.actionId = actionId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateActionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateActionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.updateActionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.updateActionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateActionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public updateActionResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updateActionResult As Boolean)
            MyBase.New
            Me.updateActionResult = updateActionResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getActionByNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getActionByName", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.getActionByNameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.getActionByNameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getActionByNameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String)
            MyBase.New
            Me.name = name
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getActionByNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getActionByNameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.getActionByNameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.getActionByNameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getActionByNameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getActionByNameResult As ActionService.action
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getActionByNameResult As ActionService.action)
            MyBase.New
            Me.getActionByNameResult = getActionByNameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getActionsByUnitIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getActionsByUnitId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.getActionsByUnitIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.getActionsByUnitIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getActionsByUnitIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public unitId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal unitId As Long)
            MyBase.New
            Me.unitId = unitId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getActionsByUnitIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getActionsByUnitIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ActionService.getActionsByUnitIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ActionService.getActionsByUnitIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getActionsByUnitIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getActionsByUnitIdResult As ActionService.ArrayOfAction
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getActionsByUnitIdResult As ActionService.ArrayOfAction)
            MyBase.New
            Me.getActionsByUnitIdResult = getActionsByUnitIdResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ActionServiceSoapChannel
        Inherits ActionService.ActionServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ActionServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of ActionService.ActionServiceSoap)
        Implements ActionService.ActionServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_ping(ByVal request As ActionService.pingRequest) As ActionService.pingResponse Implements ActionService.ActionServiceSoap.ping
            Return MyBase.Channel.ping(request)
        End Function
        
        Public Function ping() As String
            Dim inValue As ActionService.pingRequest = New ActionService.pingRequest()
            inValue.Body = New ActionService.pingRequestBody()
            Dim retVal As ActionService.pingResponse = CType(Me,ActionService.ActionServiceSoap).ping(inValue)
            Return retVal.Body.pingResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_pingAsync(ByVal request As ActionService.pingRequest) As System.Threading.Tasks.Task(Of ActionService.pingResponse) Implements ActionService.ActionServiceSoap.pingAsync
            Return MyBase.Channel.pingAsync(request)
        End Function
        
        Public Function pingAsync() As System.Threading.Tasks.Task(Of ActionService.pingResponse)
            Dim inValue As ActionService.pingRequest = New ActionService.pingRequest()
            inValue.Body = New ActionService.pingRequestBody()
            Return CType(Me,ActionService.ActionServiceSoap).pingAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_addActionByNameAndUnitId(ByVal request As ActionService.addActionByNameAndUnitIdRequest) As ActionService.addActionByNameAndUnitIdResponse Implements ActionService.ActionServiceSoap.addActionByNameAndUnitId
            Return MyBase.Channel.addActionByNameAndUnitId(request)
        End Function
        
        Public Function addActionByNameAndUnitId(ByVal name As String, ByVal unitId As Long) As ActionService.action
            Dim inValue As ActionService.addActionByNameAndUnitIdRequest = New ActionService.addActionByNameAndUnitIdRequest()
            inValue.Body = New ActionService.addActionByNameAndUnitIdRequestBody()
            inValue.Body.name = name
            inValue.Body.unitId = unitId
            Dim retVal As ActionService.addActionByNameAndUnitIdResponse = CType(Me,ActionService.ActionServiceSoap).addActionByNameAndUnitId(inValue)
            Return retVal.Body.addActionByNameAndUnitIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_addActionByNameAndUnitIdAsync(ByVal request As ActionService.addActionByNameAndUnitIdRequest) As System.Threading.Tasks.Task(Of ActionService.addActionByNameAndUnitIdResponse) Implements ActionService.ActionServiceSoap.addActionByNameAndUnitIdAsync
            Return MyBase.Channel.addActionByNameAndUnitIdAsync(request)
        End Function
        
        Public Function addActionByNameAndUnitIdAsync(ByVal name As String, ByVal unitId As Long) As System.Threading.Tasks.Task(Of ActionService.addActionByNameAndUnitIdResponse)
            Dim inValue As ActionService.addActionByNameAndUnitIdRequest = New ActionService.addActionByNameAndUnitIdRequest()
            inValue.Body = New ActionService.addActionByNameAndUnitIdRequestBody()
            inValue.Body.name = name
            inValue.Body.unitId = unitId
            Return CType(Me,ActionService.ActionServiceSoap).addActionByNameAndUnitIdAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_updateAction(ByVal request As ActionService.updateActionRequest) As ActionService.updateActionResponse Implements ActionService.ActionServiceSoap.updateAction
            Return MyBase.Channel.updateAction(request)
        End Function
        
        Public Function updateAction(ByVal name As String, ByVal unitId As Long, ByVal actionId As Long) As Boolean
            Dim inValue As ActionService.updateActionRequest = New ActionService.updateActionRequest()
            inValue.Body = New ActionService.updateActionRequestBody()
            inValue.Body.name = name
            inValue.Body.unitId = unitId
            inValue.Body.actionId = actionId
            Dim retVal As ActionService.updateActionResponse = CType(Me,ActionService.ActionServiceSoap).updateAction(inValue)
            Return retVal.Body.updateActionResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_updateActionAsync(ByVal request As ActionService.updateActionRequest) As System.Threading.Tasks.Task(Of ActionService.updateActionResponse) Implements ActionService.ActionServiceSoap.updateActionAsync
            Return MyBase.Channel.updateActionAsync(request)
        End Function
        
        Public Function updateActionAsync(ByVal name As String, ByVal unitId As Long, ByVal actionId As Long) As System.Threading.Tasks.Task(Of ActionService.updateActionResponse)
            Dim inValue As ActionService.updateActionRequest = New ActionService.updateActionRequest()
            inValue.Body = New ActionService.updateActionRequestBody()
            inValue.Body.name = name
            inValue.Body.unitId = unitId
            inValue.Body.actionId = actionId
            Return CType(Me,ActionService.ActionServiceSoap).updateActionAsync(inValue)
        End Function
        
        Public Function deleteAction(ByVal actionId As Long) As Boolean Implements ActionService.ActionServiceSoap.deleteAction
            Return MyBase.Channel.deleteAction(actionId)
        End Function
        
        Public Function deleteActionAsync(ByVal actionId As Long) As System.Threading.Tasks.Task(Of Boolean) Implements ActionService.ActionServiceSoap.deleteActionAsync
            Return MyBase.Channel.deleteActionAsync(actionId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_getActionByName(ByVal request As ActionService.getActionByNameRequest) As ActionService.getActionByNameResponse Implements ActionService.ActionServiceSoap.getActionByName
            Return MyBase.Channel.getActionByName(request)
        End Function
        
        Public Function getActionByName(ByVal name As String) As ActionService.action
            Dim inValue As ActionService.getActionByNameRequest = New ActionService.getActionByNameRequest()
            inValue.Body = New ActionService.getActionByNameRequestBody()
            inValue.Body.name = name
            Dim retVal As ActionService.getActionByNameResponse = CType(Me,ActionService.ActionServiceSoap).getActionByName(inValue)
            Return retVal.Body.getActionByNameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_getActionByNameAsync(ByVal request As ActionService.getActionByNameRequest) As System.Threading.Tasks.Task(Of ActionService.getActionByNameResponse) Implements ActionService.ActionServiceSoap.getActionByNameAsync
            Return MyBase.Channel.getActionByNameAsync(request)
        End Function
        
        Public Function getActionByNameAsync(ByVal name As String) As System.Threading.Tasks.Task(Of ActionService.getActionByNameResponse)
            Dim inValue As ActionService.getActionByNameRequest = New ActionService.getActionByNameRequest()
            inValue.Body = New ActionService.getActionByNameRequestBody()
            inValue.Body.name = name
            Return CType(Me,ActionService.ActionServiceSoap).getActionByNameAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_getActionsByUnitId(ByVal request As ActionService.getActionsByUnitIdRequest) As ActionService.getActionsByUnitIdResponse Implements ActionService.ActionServiceSoap.getActionsByUnitId
            Return MyBase.Channel.getActionsByUnitId(request)
        End Function
        
        Public Function getActionsByUnitId(ByVal unitId As Long) As ActionService.ArrayOfAction
            Dim inValue As ActionService.getActionsByUnitIdRequest = New ActionService.getActionsByUnitIdRequest()
            inValue.Body = New ActionService.getActionsByUnitIdRequestBody()
            inValue.Body.unitId = unitId
            Dim retVal As ActionService.getActionsByUnitIdResponse = CType(Me,ActionService.ActionServiceSoap).getActionsByUnitId(inValue)
            Return retVal.Body.getActionsByUnitIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ActionService_ActionServiceSoap_getActionsByUnitIdAsync(ByVal request As ActionService.getActionsByUnitIdRequest) As System.Threading.Tasks.Task(Of ActionService.getActionsByUnitIdResponse) Implements ActionService.ActionServiceSoap.getActionsByUnitIdAsync
            Return MyBase.Channel.getActionsByUnitIdAsync(request)
        End Function
        
        Public Function getActionsByUnitIdAsync(ByVal unitId As Long) As System.Threading.Tasks.Task(Of ActionService.getActionsByUnitIdResponse)
            Dim inValue As ActionService.getActionsByUnitIdRequest = New ActionService.getActionsByUnitIdRequest()
            inValue.Body = New ActionService.getActionsByUnitIdRequestBody()
            inValue.Body.unitId = unitId
            Return CType(Me,ActionService.ActionServiceSoap).getActionsByUnitIdAsync(inValue)
        End Function
    End Class
End Namespace
