'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace UnitService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="unit", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class unit
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private unit_idField As Long
        
        Private type_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property unit_id() As Long
            Get
                Return Me.unit_idField
            End Get
            Set
                If (Me.unit_idField.Equals(value) <> true) Then
                    Me.unit_idField = value
                    Me.RaisePropertyChanged("unit_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=1)>  _
        Public Property type_id() As Long
            Get
                Return Me.type_idField
            End Get
            Set
                If (Me.type_idField.Equals(value) <> true) Then
                    Me.type_idField = value
                    Me.RaisePropertyChanged("type_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="unit_type", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class unit_type
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private type_idField As Long
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private nameField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private picture_urlField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property type_id() As Long
            Get
                Return Me.type_idField
            End Get
            Set
                If (Me.type_idField.Equals(value) <> true) Then
                    Me.type_idField = value
                    Me.RaisePropertyChanged("type_id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Property name() As String
            Get
                Return Me.nameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.nameField, value) <> true) Then
                    Me.nameField = value
                    Me.RaisePropertyChanged("name")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Property picture_url() As String
            Get
                Return Me.picture_urlField
            End Get
            Set
                If (Object.ReferenceEquals(Me.picture_urlField, value) <> true) Then
                    Me.picture_urlField = value
                    Me.RaisePropertyChanged("picture_url")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfUnit", [Namespace]:="http://tempuri.org/", ItemName:="unit"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfUnit
        Inherits System.Collections.Generic.List(Of UnitService.unit)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ArrayOfUnit_type", [Namespace]:="http://tempuri.org/", ItemName:="unit_type"),  _
     System.SerializableAttribute()>  _
    Public Class ArrayOfUnit_type
        Inherits System.Collections.Generic.List(Of UnitService.unit_type)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="UnitService.UnitServiceSoap")>  _
    Public Interface UnitServiceSoap
        
        'CODEGEN: Generating message contract since element name pingResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function ping(ByVal request As UnitService.pingRequest) As UnitService.pingResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ping", ReplyAction:="*")>  _
        Function pingAsync(ByVal request As UnitService.pingRequest) As System.Threading.Tasks.Task(Of UnitService.pingResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addUnitByNameAndTypeId", ReplyAction:="*")>  _
        Function addUnitByNameAndTypeId(ByVal request As UnitService.addUnitByNameAndTypeIdRequest) As UnitService.addUnitByNameAndTypeIdResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addUnitByNameAndTypeId", ReplyAction:="*")>  _
        Function addUnitByNameAndTypeIdAsync(ByVal request As UnitService.addUnitByNameAndTypeIdRequest) As System.Threading.Tasks.Task(Of UnitService.addUnitByNameAndTypeIdResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addUnitTypeByName", ReplyAction:="*")>  _
        Function addUnitTypeByName(ByVal request As UnitService.addUnitTypeByNameRequest) As UnitService.addUnitTypeByNameResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addUnitTypeByName", ReplyAction:="*")>  _
        Function addUnitTypeByNameAsync(ByVal request As UnitService.addUnitTypeByNameRequest) As System.Threading.Tasks.Task(Of UnitService.addUnitTypeByNameResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addUnitTypeByNameAndPictureUrl", ReplyAction:="*")>  _
        Function addUnitTypeByNameAndPictureUrl(ByVal request As UnitService.addUnitTypeByNameAndPictureUrlRequest) As UnitService.addUnitTypeByNameAndPictureUrlResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/addUnitTypeByNameAndPictureUrl", ReplyAction:="*")>  _
        Function addUnitTypeByNameAndPictureUrlAsync(ByVal request As UnitService.addUnitTypeByNameAndPictureUrlRequest) As System.Threading.Tasks.Task(Of UnitService.addUnitTypeByNameAndPictureUrlResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateUnit", ReplyAction:="*")>  _
        Function updateUnit(ByVal request As UnitService.updateUnitRequest) As UnitService.updateUnitResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateUnit", ReplyAction:="*")>  _
        Function updateUnitAsync(ByVal request As UnitService.updateUnitRequest) As System.Threading.Tasks.Task(Of UnitService.updateUnitResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateUnitType", ReplyAction:="*")>  _
        Function updateUnitType(ByVal request As UnitService.updateUnitTypeRequest) As UnitService.updateUnitTypeResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/updateUnitType", ReplyAction:="*")>  _
        Function updateUnitTypeAsync(ByVal request As UnitService.updateUnitTypeRequest) As System.Threading.Tasks.Task(Of UnitService.updateUnitTypeResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deleteUnit", ReplyAction:="*")>  _
        Function deleteUnit(ByVal unitId As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deleteUnit", ReplyAction:="*")>  _
        Function deleteUnitAsync(ByVal unitId As Long) As System.Threading.Tasks.Task(Of Boolean)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deleteUnitType", ReplyAction:="*")>  _
        Function deleteUnitType(ByVal typeId As Long) As Boolean
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/deleteUnitType", ReplyAction:="*")>  _
        Function deleteUnitTypeAsync(ByVal typeId As Long) As System.Threading.Tasks.Task(Of Boolean)
        
        'CODEGEN: Generating message contract since element name getUnitResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnit", ReplyAction:="*")>  _
        Function getUnit(ByVal request As UnitService.getUnitRequest) As UnitService.getUnitResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnit", ReplyAction:="*")>  _
        Function getUnitAsync(ByVal request As UnitService.getUnitRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnitByName", ReplyAction:="*")>  _
        Function getUnitByName(ByVal request As UnitService.getUnitByNameRequest) As UnitService.getUnitByNameResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnitByName", ReplyAction:="*")>  _
        Function getUnitByNameAsync(ByVal request As UnitService.getUnitByNameRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitByNameResponse)
        
        'CODEGEN: Generating message contract since element name getUnitsResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnits", ReplyAction:="*")>  _
        Function getUnits(ByVal request As UnitService.getUnitsRequest) As UnitService.getUnitsResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnits", ReplyAction:="*")>  _
        Function getUnitsAsync(ByVal request As UnitService.getUnitsRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitsResponse)
        
        'CODEGEN: Generating message contract since element name getUnitTypeResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnitType", ReplyAction:="*")>  _
        Function getUnitType(ByVal request As UnitService.getUnitTypeRequest) As UnitService.getUnitTypeResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnitType", ReplyAction:="*")>  _
        Function getUnitTypeAsync(ByVal request As UnitService.getUnitTypeRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitTypeResponse)
        
        'CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnitTypeByName", ReplyAction:="*")>  _
        Function getUnitTypeByName(ByVal request As UnitService.getUnitTypeByNameRequest) As UnitService.getUnitTypeByNameResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnitTypeByName", ReplyAction:="*")>  _
        Function getUnitTypeByNameAsync(ByVal request As UnitService.getUnitTypeByNameRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitTypeByNameResponse)
        
        'CODEGEN: Generating message contract since element name getUnitTypesResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnitTypes", ReplyAction:="*")>  _
        Function getUnitTypes(ByVal request As UnitService.getUnitTypesRequest) As UnitService.getUnitTypesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getUnitTypes", ReplyAction:="*")>  _
        Function getUnitTypesAsync(ByVal request As UnitService.getUnitTypesRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitTypesResponse)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getTotalAmountByUnitId", ReplyAction:="*")>  _
        Function getTotalAmountByUnitId(ByVal unitId As Long) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getTotalAmountByUnitId", ReplyAction:="*")>  _
        Function getTotalAmountByUnitIdAsync(ByVal unitId As Long) As System.Threading.Tasks.Task(Of Integer)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getTotalAmount", ReplyAction:="*")>  _
        Function getTotalAmount() As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/getTotalAmount", ReplyAction:="*")>  _
        Function getTotalAmountAsync() As System.Threading.Tasks.Task(Of Integer)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class pingRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ping", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.pingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.pingRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class pingRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class pingResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="pingResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.pingResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.pingResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class pingResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public pingResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal pingResult As String)
            MyBase.New
            Me.pingResult = pingResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addUnitByNameAndTypeIdRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addUnitByNameAndTypeId", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.addUnitByNameAndTypeIdRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.addUnitByNameAndTypeIdRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addUnitByNameAndTypeIdRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public typeId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String, ByVal typeId As Long)
            MyBase.New
            Me.name = name
            Me.typeId = typeId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addUnitByNameAndTypeIdResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addUnitByNameAndTypeIdResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.addUnitByNameAndTypeIdResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.addUnitByNameAndTypeIdResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addUnitByNameAndTypeIdResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public addUnitByNameAndTypeIdResult As UnitService.unit
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal addUnitByNameAndTypeIdResult As UnitService.unit)
            MyBase.New
            Me.addUnitByNameAndTypeIdResult = addUnitByNameAndTypeIdResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addUnitTypeByNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addUnitTypeByName", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.addUnitTypeByNameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.addUnitTypeByNameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addUnitTypeByNameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String)
            MyBase.New
            Me.name = name
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addUnitTypeByNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addUnitTypeByNameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.addUnitTypeByNameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.addUnitTypeByNameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addUnitTypeByNameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public addUnitTypeByNameResult As UnitService.unit_type
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal addUnitTypeByNameResult As UnitService.unit_type)
            MyBase.New
            Me.addUnitTypeByNameResult = addUnitTypeByNameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addUnitTypeByNameAndPictureUrlRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addUnitTypeByNameAndPictureUrl", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.addUnitTypeByNameAndPictureUrlRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.addUnitTypeByNameAndPictureUrlRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addUnitTypeByNameAndPictureUrlRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pictureUrl As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String, ByVal pictureUrl As String)
            MyBase.New
            Me.name = name
            Me.pictureUrl = pictureUrl
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class addUnitTypeByNameAndPictureUrlResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="addUnitTypeByNameAndPictureUrlResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.addUnitTypeByNameAndPictureUrlResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.addUnitTypeByNameAndPictureUrlResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class addUnitTypeByNameAndPictureUrlResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public addUnitTypeByNameAndPictureUrlResult As UnitService.unit_type
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal addUnitTypeByNameAndPictureUrlResult As UnitService.unit_type)
            MyBase.New
            Me.addUnitTypeByNameAndPictureUrlResult = addUnitTypeByNameAndPictureUrlResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateUnitRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateUnit", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.updateUnitRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.updateUnitRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateUnitRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=1)>  _
        Public typeId As Long
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public unitId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String, ByVal typeId As Long, ByVal unitId As Long)
            MyBase.New
            Me.name = name
            Me.typeId = typeId
            Me.unitId = unitId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateUnitResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateUnitResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.updateUnitResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.updateUnitResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateUnitResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public updateUnitResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updateUnitResult As Boolean)
            MyBase.New
            Me.updateUnitResult = updateUnitResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateUnitTypeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateUnitType", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.updateUnitTypeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.updateUnitTypeRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateUnitTypeRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public pictureUrl As String
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=2)>  _
        Public typeId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String, ByVal pictureUrl As String, ByVal typeId As Long)
            MyBase.New
            Me.name = name
            Me.pictureUrl = pictureUrl
            Me.typeId = typeId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class updateUnitTypeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="updateUnitTypeResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.updateUnitTypeResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.updateUnitTypeResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class updateUnitTypeResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public updateUnitTypeResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal updateUnitTypeResult As Boolean)
            MyBase.New
            Me.updateUnitTypeResult = updateUnitTypeResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnit", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public unitId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal unitId As Long)
            MyBase.New
            Me.unitId = unitId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getUnitResult As UnitService.unit
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUnitResult As UnitService.unit)
            MyBase.New
            Me.getUnitResult = getUnitResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitByNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitByName", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitByNameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitByNameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitByNameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String)
            MyBase.New
            Me.name = name
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitByNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitByNameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitByNameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitByNameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitByNameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getUnitByNameResult As UnitService.unit
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUnitByNameResult As UnitService.unit)
            MyBase.New
            Me.getUnitByNameResult = getUnitByNameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitsRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnits", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitsRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class getUnitsRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitsResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitsResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitsResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitsResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitsResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getUnitsResult As UnitService.ArrayOfUnit
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUnitsResult As UnitService.ArrayOfUnit)
            MyBase.New
            Me.getUnitsResult = getUnitsResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitTypeRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitType", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitTypeRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitTypeRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitTypeRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public typeId As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal typeId As Long)
            MyBase.New
            Me.typeId = typeId
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitTypeResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitTypeResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitTypeResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitTypeResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitTypeResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getUnitTypeResult As UnitService.unit_type
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUnitTypeResult As UnitService.unit_type)
            MyBase.New
            Me.getUnitTypeResult = getUnitTypeResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitTypeByNameRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitTypeByName", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitTypeByNameRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitTypeByNameRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitTypeByNameRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public name As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal name As String)
            MyBase.New
            Me.name = name
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitTypeByNameResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitTypeByNameResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitTypeByNameResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitTypeByNameResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitTypeByNameResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getUnitTypeByNameResult As UnitService.unit_type
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUnitTypeByNameResult As UnitService.unit_type)
            MyBase.New
            Me.getUnitTypeByNameResult = getUnitTypeByNameResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitTypesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitTypes", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitTypesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitTypesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class getUnitTypesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class getUnitTypesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="getUnitTypesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As UnitService.getUnitTypesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As UnitService.getUnitTypesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class getUnitTypesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public getUnitTypesResult As UnitService.ArrayOfUnit_type
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal getUnitTypesResult As UnitService.ArrayOfUnit_type)
            MyBase.New
            Me.getUnitTypesResult = getUnitTypesResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UnitServiceSoapChannel
        Inherits UnitService.UnitServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UnitServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of UnitService.UnitServiceSoap)
        Implements UnitService.UnitServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_ping(ByVal request As UnitService.pingRequest) As UnitService.pingResponse Implements UnitService.UnitServiceSoap.ping
            Return MyBase.Channel.ping(request)
        End Function
        
        Public Function ping() As String
            Dim inValue As UnitService.pingRequest = New UnitService.pingRequest()
            inValue.Body = New UnitService.pingRequestBody()
            Dim retVal As UnitService.pingResponse = CType(Me,UnitService.UnitServiceSoap).ping(inValue)
            Return retVal.Body.pingResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_pingAsync(ByVal request As UnitService.pingRequest) As System.Threading.Tasks.Task(Of UnitService.pingResponse) Implements UnitService.UnitServiceSoap.pingAsync
            Return MyBase.Channel.pingAsync(request)
        End Function
        
        Public Function pingAsync() As System.Threading.Tasks.Task(Of UnitService.pingResponse)
            Dim inValue As UnitService.pingRequest = New UnitService.pingRequest()
            inValue.Body = New UnitService.pingRequestBody()
            Return CType(Me,UnitService.UnitServiceSoap).pingAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_addUnitByNameAndTypeId(ByVal request As UnitService.addUnitByNameAndTypeIdRequest) As UnitService.addUnitByNameAndTypeIdResponse Implements UnitService.UnitServiceSoap.addUnitByNameAndTypeId
            Return MyBase.Channel.addUnitByNameAndTypeId(request)
        End Function
        
        Public Function addUnitByNameAndTypeId(ByVal name As String, ByVal typeId As Long) As UnitService.unit
            Dim inValue As UnitService.addUnitByNameAndTypeIdRequest = New UnitService.addUnitByNameAndTypeIdRequest()
            inValue.Body = New UnitService.addUnitByNameAndTypeIdRequestBody()
            inValue.Body.name = name
            inValue.Body.typeId = typeId
            Dim retVal As UnitService.addUnitByNameAndTypeIdResponse = CType(Me,UnitService.UnitServiceSoap).addUnitByNameAndTypeId(inValue)
            Return retVal.Body.addUnitByNameAndTypeIdResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_addUnitByNameAndTypeIdAsync(ByVal request As UnitService.addUnitByNameAndTypeIdRequest) As System.Threading.Tasks.Task(Of UnitService.addUnitByNameAndTypeIdResponse) Implements UnitService.UnitServiceSoap.addUnitByNameAndTypeIdAsync
            Return MyBase.Channel.addUnitByNameAndTypeIdAsync(request)
        End Function
        
        Public Function addUnitByNameAndTypeIdAsync(ByVal name As String, ByVal typeId As Long) As System.Threading.Tasks.Task(Of UnitService.addUnitByNameAndTypeIdResponse)
            Dim inValue As UnitService.addUnitByNameAndTypeIdRequest = New UnitService.addUnitByNameAndTypeIdRequest()
            inValue.Body = New UnitService.addUnitByNameAndTypeIdRequestBody()
            inValue.Body.name = name
            inValue.Body.typeId = typeId
            Return CType(Me,UnitService.UnitServiceSoap).addUnitByNameAndTypeIdAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_addUnitTypeByName(ByVal request As UnitService.addUnitTypeByNameRequest) As UnitService.addUnitTypeByNameResponse Implements UnitService.UnitServiceSoap.addUnitTypeByName
            Return MyBase.Channel.addUnitTypeByName(request)
        End Function
        
        Public Function addUnitTypeByName(ByVal name As String) As UnitService.unit_type
            Dim inValue As UnitService.addUnitTypeByNameRequest = New UnitService.addUnitTypeByNameRequest()
            inValue.Body = New UnitService.addUnitTypeByNameRequestBody()
            inValue.Body.name = name
            Dim retVal As UnitService.addUnitTypeByNameResponse = CType(Me,UnitService.UnitServiceSoap).addUnitTypeByName(inValue)
            Return retVal.Body.addUnitTypeByNameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_addUnitTypeByNameAsync(ByVal request As UnitService.addUnitTypeByNameRequest) As System.Threading.Tasks.Task(Of UnitService.addUnitTypeByNameResponse) Implements UnitService.UnitServiceSoap.addUnitTypeByNameAsync
            Return MyBase.Channel.addUnitTypeByNameAsync(request)
        End Function
        
        Public Function addUnitTypeByNameAsync(ByVal name As String) As System.Threading.Tasks.Task(Of UnitService.addUnitTypeByNameResponse)
            Dim inValue As UnitService.addUnitTypeByNameRequest = New UnitService.addUnitTypeByNameRequest()
            inValue.Body = New UnitService.addUnitTypeByNameRequestBody()
            inValue.Body.name = name
            Return CType(Me,UnitService.UnitServiceSoap).addUnitTypeByNameAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_addUnitTypeByNameAndPictureUrl(ByVal request As UnitService.addUnitTypeByNameAndPictureUrlRequest) As UnitService.addUnitTypeByNameAndPictureUrlResponse Implements UnitService.UnitServiceSoap.addUnitTypeByNameAndPictureUrl
            Return MyBase.Channel.addUnitTypeByNameAndPictureUrl(request)
        End Function
        
        Public Function addUnitTypeByNameAndPictureUrl(ByVal name As String, ByVal pictureUrl As String) As UnitService.unit_type
            Dim inValue As UnitService.addUnitTypeByNameAndPictureUrlRequest = New UnitService.addUnitTypeByNameAndPictureUrlRequest()
            inValue.Body = New UnitService.addUnitTypeByNameAndPictureUrlRequestBody()
            inValue.Body.name = name
            inValue.Body.pictureUrl = pictureUrl
            Dim retVal As UnitService.addUnitTypeByNameAndPictureUrlResponse = CType(Me,UnitService.UnitServiceSoap).addUnitTypeByNameAndPictureUrl(inValue)
            Return retVal.Body.addUnitTypeByNameAndPictureUrlResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_addUnitTypeByNameAndPictureUrlAsync(ByVal request As UnitService.addUnitTypeByNameAndPictureUrlRequest) As System.Threading.Tasks.Task(Of UnitService.addUnitTypeByNameAndPictureUrlResponse) Implements UnitService.UnitServiceSoap.addUnitTypeByNameAndPictureUrlAsync
            Return MyBase.Channel.addUnitTypeByNameAndPictureUrlAsync(request)
        End Function
        
        Public Function addUnitTypeByNameAndPictureUrlAsync(ByVal name As String, ByVal pictureUrl As String) As System.Threading.Tasks.Task(Of UnitService.addUnitTypeByNameAndPictureUrlResponse)
            Dim inValue As UnitService.addUnitTypeByNameAndPictureUrlRequest = New UnitService.addUnitTypeByNameAndPictureUrlRequest()
            inValue.Body = New UnitService.addUnitTypeByNameAndPictureUrlRequestBody()
            inValue.Body.name = name
            inValue.Body.pictureUrl = pictureUrl
            Return CType(Me,UnitService.UnitServiceSoap).addUnitTypeByNameAndPictureUrlAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_updateUnit(ByVal request As UnitService.updateUnitRequest) As UnitService.updateUnitResponse Implements UnitService.UnitServiceSoap.updateUnit
            Return MyBase.Channel.updateUnit(request)
        End Function
        
        Public Function updateUnit(ByVal name As String, ByVal typeId As Long, ByVal unitId As Long) As Boolean
            Dim inValue As UnitService.updateUnitRequest = New UnitService.updateUnitRequest()
            inValue.Body = New UnitService.updateUnitRequestBody()
            inValue.Body.name = name
            inValue.Body.typeId = typeId
            inValue.Body.unitId = unitId
            Dim retVal As UnitService.updateUnitResponse = CType(Me,UnitService.UnitServiceSoap).updateUnit(inValue)
            Return retVal.Body.updateUnitResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_updateUnitAsync(ByVal request As UnitService.updateUnitRequest) As System.Threading.Tasks.Task(Of UnitService.updateUnitResponse) Implements UnitService.UnitServiceSoap.updateUnitAsync
            Return MyBase.Channel.updateUnitAsync(request)
        End Function
        
        Public Function updateUnitAsync(ByVal name As String, ByVal typeId As Long, ByVal unitId As Long) As System.Threading.Tasks.Task(Of UnitService.updateUnitResponse)
            Dim inValue As UnitService.updateUnitRequest = New UnitService.updateUnitRequest()
            inValue.Body = New UnitService.updateUnitRequestBody()
            inValue.Body.name = name
            inValue.Body.typeId = typeId
            inValue.Body.unitId = unitId
            Return CType(Me,UnitService.UnitServiceSoap).updateUnitAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_updateUnitType(ByVal request As UnitService.updateUnitTypeRequest) As UnitService.updateUnitTypeResponse Implements UnitService.UnitServiceSoap.updateUnitType
            Return MyBase.Channel.updateUnitType(request)
        End Function
        
        Public Function updateUnitType(ByVal name As String, ByVal pictureUrl As String, ByVal typeId As Long) As Boolean
            Dim inValue As UnitService.updateUnitTypeRequest = New UnitService.updateUnitTypeRequest()
            inValue.Body = New UnitService.updateUnitTypeRequestBody()
            inValue.Body.name = name
            inValue.Body.pictureUrl = pictureUrl
            inValue.Body.typeId = typeId
            Dim retVal As UnitService.updateUnitTypeResponse = CType(Me,UnitService.UnitServiceSoap).updateUnitType(inValue)
            Return retVal.Body.updateUnitTypeResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_updateUnitTypeAsync(ByVal request As UnitService.updateUnitTypeRequest) As System.Threading.Tasks.Task(Of UnitService.updateUnitTypeResponse) Implements UnitService.UnitServiceSoap.updateUnitTypeAsync
            Return MyBase.Channel.updateUnitTypeAsync(request)
        End Function
        
        Public Function updateUnitTypeAsync(ByVal name As String, ByVal pictureUrl As String, ByVal typeId As Long) As System.Threading.Tasks.Task(Of UnitService.updateUnitTypeResponse)
            Dim inValue As UnitService.updateUnitTypeRequest = New UnitService.updateUnitTypeRequest()
            inValue.Body = New UnitService.updateUnitTypeRequestBody()
            inValue.Body.name = name
            inValue.Body.pictureUrl = pictureUrl
            inValue.Body.typeId = typeId
            Return CType(Me,UnitService.UnitServiceSoap).updateUnitTypeAsync(inValue)
        End Function
        
        Public Function deleteUnit(ByVal unitId As Long) As Boolean Implements UnitService.UnitServiceSoap.deleteUnit
            Return MyBase.Channel.deleteUnit(unitId)
        End Function
        
        Public Function deleteUnitAsync(ByVal unitId As Long) As System.Threading.Tasks.Task(Of Boolean) Implements UnitService.UnitServiceSoap.deleteUnitAsync
            Return MyBase.Channel.deleteUnitAsync(unitId)
        End Function
        
        Public Function deleteUnitType(ByVal typeId As Long) As Boolean Implements UnitService.UnitServiceSoap.deleteUnitType
            Return MyBase.Channel.deleteUnitType(typeId)
        End Function
        
        Public Function deleteUnitTypeAsync(ByVal typeId As Long) As System.Threading.Tasks.Task(Of Boolean) Implements UnitService.UnitServiceSoap.deleteUnitTypeAsync
            Return MyBase.Channel.deleteUnitTypeAsync(typeId)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnit(ByVal request As UnitService.getUnitRequest) As UnitService.getUnitResponse Implements UnitService.UnitServiceSoap.getUnit
            Return MyBase.Channel.getUnit(request)
        End Function
        
        Public Function getUnit(ByVal unitId As Long) As UnitService.unit
            Dim inValue As UnitService.getUnitRequest = New UnitService.getUnitRequest()
            inValue.Body = New UnitService.getUnitRequestBody()
            inValue.Body.unitId = unitId
            Dim retVal As UnitService.getUnitResponse = CType(Me,UnitService.UnitServiceSoap).getUnit(inValue)
            Return retVal.Body.getUnitResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitAsync(ByVal request As UnitService.getUnitRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitResponse) Implements UnitService.UnitServiceSoap.getUnitAsync
            Return MyBase.Channel.getUnitAsync(request)
        End Function
        
        Public Function getUnitAsync(ByVal unitId As Long) As System.Threading.Tasks.Task(Of UnitService.getUnitResponse)
            Dim inValue As UnitService.getUnitRequest = New UnitService.getUnitRequest()
            inValue.Body = New UnitService.getUnitRequestBody()
            inValue.Body.unitId = unitId
            Return CType(Me,UnitService.UnitServiceSoap).getUnitAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitByName(ByVal request As UnitService.getUnitByNameRequest) As UnitService.getUnitByNameResponse Implements UnitService.UnitServiceSoap.getUnitByName
            Return MyBase.Channel.getUnitByName(request)
        End Function
        
        Public Function getUnitByName(ByVal name As String) As UnitService.unit
            Dim inValue As UnitService.getUnitByNameRequest = New UnitService.getUnitByNameRequest()
            inValue.Body = New UnitService.getUnitByNameRequestBody()
            inValue.Body.name = name
            Dim retVal As UnitService.getUnitByNameResponse = CType(Me,UnitService.UnitServiceSoap).getUnitByName(inValue)
            Return retVal.Body.getUnitByNameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitByNameAsync(ByVal request As UnitService.getUnitByNameRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitByNameResponse) Implements UnitService.UnitServiceSoap.getUnitByNameAsync
            Return MyBase.Channel.getUnitByNameAsync(request)
        End Function
        
        Public Function getUnitByNameAsync(ByVal name As String) As System.Threading.Tasks.Task(Of UnitService.getUnitByNameResponse)
            Dim inValue As UnitService.getUnitByNameRequest = New UnitService.getUnitByNameRequest()
            inValue.Body = New UnitService.getUnitByNameRequestBody()
            inValue.Body.name = name
            Return CType(Me,UnitService.UnitServiceSoap).getUnitByNameAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnits(ByVal request As UnitService.getUnitsRequest) As UnitService.getUnitsResponse Implements UnitService.UnitServiceSoap.getUnits
            Return MyBase.Channel.getUnits(request)
        End Function
        
        Public Function getUnits() As UnitService.ArrayOfUnit
            Dim inValue As UnitService.getUnitsRequest = New UnitService.getUnitsRequest()
            inValue.Body = New UnitService.getUnitsRequestBody()
            Dim retVal As UnitService.getUnitsResponse = CType(Me,UnitService.UnitServiceSoap).getUnits(inValue)
            Return retVal.Body.getUnitsResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitsAsync(ByVal request As UnitService.getUnitsRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitsResponse) Implements UnitService.UnitServiceSoap.getUnitsAsync
            Return MyBase.Channel.getUnitsAsync(request)
        End Function
        
        Public Function getUnitsAsync() As System.Threading.Tasks.Task(Of UnitService.getUnitsResponse)
            Dim inValue As UnitService.getUnitsRequest = New UnitService.getUnitsRequest()
            inValue.Body = New UnitService.getUnitsRequestBody()
            Return CType(Me,UnitService.UnitServiceSoap).getUnitsAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitType(ByVal request As UnitService.getUnitTypeRequest) As UnitService.getUnitTypeResponse Implements UnitService.UnitServiceSoap.getUnitType
            Return MyBase.Channel.getUnitType(request)
        End Function
        
        Public Function getUnitType(ByVal typeId As Long) As UnitService.unit_type
            Dim inValue As UnitService.getUnitTypeRequest = New UnitService.getUnitTypeRequest()
            inValue.Body = New UnitService.getUnitTypeRequestBody()
            inValue.Body.typeId = typeId
            Dim retVal As UnitService.getUnitTypeResponse = CType(Me,UnitService.UnitServiceSoap).getUnitType(inValue)
            Return retVal.Body.getUnitTypeResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitTypeAsync(ByVal request As UnitService.getUnitTypeRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitTypeResponse) Implements UnitService.UnitServiceSoap.getUnitTypeAsync
            Return MyBase.Channel.getUnitTypeAsync(request)
        End Function
        
        Public Function getUnitTypeAsync(ByVal typeId As Long) As System.Threading.Tasks.Task(Of UnitService.getUnitTypeResponse)
            Dim inValue As UnitService.getUnitTypeRequest = New UnitService.getUnitTypeRequest()
            inValue.Body = New UnitService.getUnitTypeRequestBody()
            inValue.Body.typeId = typeId
            Return CType(Me,UnitService.UnitServiceSoap).getUnitTypeAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitTypeByName(ByVal request As UnitService.getUnitTypeByNameRequest) As UnitService.getUnitTypeByNameResponse Implements UnitService.UnitServiceSoap.getUnitTypeByName
            Return MyBase.Channel.getUnitTypeByName(request)
        End Function
        
        Public Function getUnitTypeByName(ByVal name As String) As UnitService.unit_type
            Dim inValue As UnitService.getUnitTypeByNameRequest = New UnitService.getUnitTypeByNameRequest()
            inValue.Body = New UnitService.getUnitTypeByNameRequestBody()
            inValue.Body.name = name
            Dim retVal As UnitService.getUnitTypeByNameResponse = CType(Me,UnitService.UnitServiceSoap).getUnitTypeByName(inValue)
            Return retVal.Body.getUnitTypeByNameResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitTypeByNameAsync(ByVal request As UnitService.getUnitTypeByNameRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitTypeByNameResponse) Implements UnitService.UnitServiceSoap.getUnitTypeByNameAsync
            Return MyBase.Channel.getUnitTypeByNameAsync(request)
        End Function
        
        Public Function getUnitTypeByNameAsync(ByVal name As String) As System.Threading.Tasks.Task(Of UnitService.getUnitTypeByNameResponse)
            Dim inValue As UnitService.getUnitTypeByNameRequest = New UnitService.getUnitTypeByNameRequest()
            inValue.Body = New UnitService.getUnitTypeByNameRequestBody()
            inValue.Body.name = name
            Return CType(Me,UnitService.UnitServiceSoap).getUnitTypeByNameAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitTypes(ByVal request As UnitService.getUnitTypesRequest) As UnitService.getUnitTypesResponse Implements UnitService.UnitServiceSoap.getUnitTypes
            Return MyBase.Channel.getUnitTypes(request)
        End Function
        
        Public Function getUnitTypes() As UnitService.ArrayOfUnit_type
            Dim inValue As UnitService.getUnitTypesRequest = New UnitService.getUnitTypesRequest()
            inValue.Body = New UnitService.getUnitTypesRequestBody()
            Dim retVal As UnitService.getUnitTypesResponse = CType(Me,UnitService.UnitServiceSoap).getUnitTypes(inValue)
            Return retVal.Body.getUnitTypesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function UnitService_UnitServiceSoap_getUnitTypesAsync(ByVal request As UnitService.getUnitTypesRequest) As System.Threading.Tasks.Task(Of UnitService.getUnitTypesResponse) Implements UnitService.UnitServiceSoap.getUnitTypesAsync
            Return MyBase.Channel.getUnitTypesAsync(request)
        End Function
        
        Public Function getUnitTypesAsync() As System.Threading.Tasks.Task(Of UnitService.getUnitTypesResponse)
            Dim inValue As UnitService.getUnitTypesRequest = New UnitService.getUnitTypesRequest()
            inValue.Body = New UnitService.getUnitTypesRequestBody()
            Return CType(Me,UnitService.UnitServiceSoap).getUnitTypesAsync(inValue)
        End Function
        
        Public Function getTotalAmountByUnitId(ByVal unitId As Long) As Integer Implements UnitService.UnitServiceSoap.getTotalAmountByUnitId
            Return MyBase.Channel.getTotalAmountByUnitId(unitId)
        End Function
        
        Public Function getTotalAmountByUnitIdAsync(ByVal unitId As Long) As System.Threading.Tasks.Task(Of Integer) Implements UnitService.UnitServiceSoap.getTotalAmountByUnitIdAsync
            Return MyBase.Channel.getTotalAmountByUnitIdAsync(unitId)
        End Function
        
        Public Function getTotalAmount() As Integer Implements UnitService.UnitServiceSoap.getTotalAmount
            Return MyBase.Channel.getTotalAmount
        End Function
        
        Public Function getTotalAmountAsync() As System.Threading.Tasks.Task(Of Integer) Implements UnitService.UnitServiceSoap.getTotalAmountAsync
            Return MyBase.Channel.getTotalAmountAsync
        End Function
    End Class
End Namespace
