'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class [step]
    Public Property step_id As Long
    Public Property action_id As Long
    Public Property tag_id As Nullable(Of Long)
    Public Property text As String
    Public Property priority As Nullable(Of Integer)
    Public Property cron As String
    Public Property amount As Nullable(Of Integer)
    Public Property checked As String
    Public Property description As String

End Class
